### ISSUE TITLE
AndroidX Fragments are not supported

### ISSUE THREAD

**Issue by MarcinOrlowski** [sockeqwe/fragmentargs#102]
It seems androidx.* is not supported as I am getting

    error: FragmentWithArgs can only be used on fragments, but xxxxxx is not a subclass of fragment

which seems to be originated from [ArgProcessor.java line 131](https://github.com/sockeqwe/fragmentargs/blob/f26ac54e7b336cbb89466301b2a64aa5543c43a8/processor/src/main/java/com/hannesdorfmann/fragmentargs/processor/ArgProcessor.java#L131)

        TYPE_FRAGMENT = elementUtils.getTypeElement("android.app.Fragment");
        TYPE_SUPPORT_FRAGMENT =
              elementUtils.getTypeElement("android.support.v4.app.Fragment");

**Comment by sockeqwe** [comment]
Yep, should be easy to add.support for androidx fragments

Marcin Orlowski <notifications@github.com> schrieb am Sa., 12. Mai 2018,
01:06:

**Comment by AndreasBoehm** [comment]
Because of the changed imports for `@Nullable` and `@NonNull` annotations i would suggest to add a annotationProcessorArgument like `useAndroidXSupportAnnotations` to switch from `android.support.annotations` to `androidx.annotations`.

What do you think @sockeqwe ?

**Comment by sockeqwe** [comment]
Hm, good question. What about Mixed projects (use both old support library and androidx). I think we can automatically detect if fragment is a support fragment or androidx fragment and use the corresponding annotation. Not sure about platform fragments (android.app.Fragment)  though. Any thoughts?
