### ISSUE TITLE
Support incremental annotation processing

### ISSUE THREAD

**Issue by pandelisgreen13** [sockeqwe/fragmentargs#111]
Gradle latest versions provides support for incremental annotation processing.
https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

It would be great if the FragmentArgs annotation processor could opt into this :)

**Comment by SteliosElaiotrivaris** [comment]
any updates for this ?

**Comment by sockeqwe** [comment]
Feel free to create a PR to add support for this

SteliosElaiotrivaris <notifications@github.com> schrieb am Sa., 22. Feb.
2020, 12:46:

**Comment by HarisHoulis** [comment]
@sockeqwe 
Hi,
Have you given any thought regarding the category the processor belongs too, based on the Gradle [docs](https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing)?

**Comment by HarisHoulis** [comment]
Hi @sockeqwe,
Can you take a look at [this](https://github.com/sockeqwe/fragmentargs/pull/113) PR, that solves the above issue? Thanks in advance.
