### ISSUE TITLE
Add support for Properties in order to support Kotlin

### ISSUE THREAD

**Issue by dalewking** [sockeqwe/fragmentargs#21]
Kotlin does not generate non-private fields. You define properties from which is will generate a private field (if needed) and get/set methods. To support kotlin you would need to support these two scenarios:

    private @Arg SomeType value;
    public SomeType getValue();
    public setValue(SometType v)

and 

    public @Arg SomeType getValue();
    public @Arg setValue(SomeType v)

The java.beans.Introspector class would be of use here.

For reference here is the Kotlin documentation for properties: http://kotlinlang.org/docs/reference/properties.html

**Comment by sockeqwe** [comment]
Thanks for your hints and information. It's on my TODO list. Unfortunately, I'm busier than I wanted to. I don't think that I found time for that before end of July. 

I guess to support both Kotlin and Java there will be two separated annotation processors for Kotlin and Java both supporting the same annotation but generating different files. It's just a first idea. I have to elaborate and research a little bit more.

**Comment by dalewking** [comment]
No there would not need to be separate annotation processors for Kotlin and Java. As of the just released M12 version Kotlin has Kapt which is really just a front end for Java annotation processor so that any Java annotation processor will see both annotated Java classes and Kotlin classes.

There are two primary things that differentiate them however. The first as a I have described is that Kotlin defines properties not raw fields. To access them from another class you have to use get/set methods. Supporting properties would also have some benefit to plan Java code to allow code to be executed in the setter.

The other limitation, which they plan to fix, is that any classes generated by the annotation processor cannot be accessed directly from Kotlin. In terms of FragmentArgs you could not access the Builder class directly from Kotlin and would have to wrap access to it in Java code, but that limitation should eventually go away.

**Comment by sockeqwe** [comment]
I know. What I meant was that kotlin needs support for getter and setter and I would like to avoid them on java, because I don't want that people use setter and getters for arguments. From my point of view Arguments shouldn't be set dynamically nor accessible per default from other classes. 

We will see ...

**Comment by dalewking** [comment]
Meant to link to info for Kapt: http://blog.jetbrains.com/kotlin/2015/05/kapt-annotation-processing-for-kotlin/

I see no reason to not allow it in Java. If the user never uses it, it has no negative impact on the generated code and only really impacts the annotation processor.

In reality even with fields the arguments are accessible from other classes since you can't make them private. So using getter/setter has no real impact on accessiblity of the value. You can control the visibility of the getter/setter methods the same as you do currently with the field.

**Comment by sockeqwe** [comment]
Just use kotlin's `lateinit` and everything works properly:

```kotlin
public class TestFragment : Fragment() {

    @Arg lateinit val foo: String

}
```

**Comment by dalewking** [comment]
Yes, Kotlin does now provide a way around this (it didn't at the time this issue was created), but for the benefit of anyone who later stumbles on this thread, lateinit for val will no longer be supported. See the following link which says, "from now on, only vars can be marked lateinit":

http://blog.jetbrains.com/kotlin/2015/09/call-for-feedback-java-statics-result-expressions-and-more/

**Comment by sockeqwe** [comment]
That makes sense! Thanks!

**Comment by sockeqwe** [comment]
FragmentArgs supports now automatically detecting setter methods for an annotated value. Works with  kotlin `1.0-beta1-rc1`.
