### ISSUE TITLE
Build fragment without args

### ISSUE THREAD

**Issue by bryant1410** [sockeqwe/fragmentargs#32]
In order to build all the fragments in the same way, I think it would be nice if they can be built when they have no arguments, which I see is not working. The workaround I find is to use `@FragmentArgsInherited`, but the name is not the best. Maybe call it `@FragmentArgs`, with an optional boolean attribute `inhereted`

**Comment by sockeqwe** [comment]
whats the benefit of having a builder without arguments at all? why not simply use `new MyFragment()` directly instead of `new MyFragmentBuilder().build()`

**Comment by bryant1410** [comment]
As I said, to treat all the fragments the same way. So, if there is a change, the impact is minumum

**Comment by sockeqwe** [comment]
Agree, it wouldn't hurt to add this with the next release (first week of october)

**Comment by bryant1410** [comment]
:+1: :smiley:

**Comment by bryant1410** [comment]
As I originally said, IMO the best way would be to rename `FragmentArgsInherited` to `FragmentArgs` and add the optional boolean flag `inherit`. However, it would obviously break compatibility.

**Comment by sockeqwe** [comment]
yes, I will mark `@FragmentArgsInherited` as deprecated and will introduce a new one `@FragmentArgs`. By keeping both I should be able to keep backward compatibility

**Comment by bryant1410** [comment]
Sounds good
