### ISSUE TITLE
Fragments with same name in a package

### ISSUE THREAD

**Issue by madki** [sockeqwe/fragmentargs#33]
Although this seems to be a ridiculous use case there is a problem with having two fragments with the same name in a package. Consider the following case:

``` java
package com.example

@FragmentsWithArgs
public TestFragment extends Fragment {
  @Arg int one;
}
```

``` java
package com.example

public TestActivity extends Activity {
  ...
  @FragmentsWithArgs
  public static class TestFragment extends Fragment {
    @Arg int two;
  }
}
```

Both the above fragments have the same name and same package. So it throws an error `error: duplicate class:`

I was just playing around with the library and came across it. I don't think it's a very good idea to name two fragments the same in the first place.

**Comment by sockeqwe** [comment]
I see. I think this shouldn't be to hard to fix. At the moment I only consider the package name to save the Builder into. Obviously the Builder should be in `com.example.TestActivity.TestFragmentBuilder`. 

As you have already said, it's not a common use case, so I won't publish a hotfix for that. I will fix it with the next update when 2-3 issues / enhancements come together.

Thanks for reporting!

**Comment by themadhukiran** [comment]
Is it possible to get the builder to be `com.example.TestActivity.TestFragmentBuilder`, that means `TestFragmentBuilder` has to be inner class of `TestActivity` right?

**Comment by sockeqwe** [comment]
yes as a inner static public class. I have to verify that, but I think that should be possible with annotation processing

**Comment by themadhukiran** [comment]
But `TestActivity` already exists, so we can't modify it right? Or that's what I understood from reading your blog.

**Comment by sockeqwe** [comment]
No that's true, you can't modify an existing class. But I think adding a inner class is not really changing the original `TestActivity` source file. As far as I know it's just another canonical name and the java compiler doesn't really care if the inner class source code is really inside `TestActivity` as long as the full qualified name / canonical name is correct it should work. But as already said, I have to verify that.

**Comment by themadhukiran** [comment]
I tried doing it in the following way. It's not working:
```java
TypeSpec innerFragment = TypeSpec.classBuilder("TestFragment")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .addField(int.class, "one")
                    .build();

TypeSpec testActivity = TypeSpec.classBuilder("TestActivity")
                    .addModifiers(Modifier.PUBLIC)
                    .addType(innerFragment)
                    .build();

 try {
     JavaFile.builder("com.example", testActivity).build().writeTo(filer);
  }  catch (IOException e) {
      e.printStackTrace();
  }
```
This created another class in the same package and resulted in `error: duplicate class: com.example.TestActivity`. Is there any other way for creating inner classes ?

**Comment by sockeqwe** [comment]
Yeah, you definitely are regenerating a source file `TestActivity` which obviously already exists. Hence the error message. You don't have to generate `TestActivity`. You only have to put the `TestFragment` into a file called `com.example.TestActivity$TestFragment`. This should be the equivalent to have it written by hand as inner class in java. Perhaps `JavaPoet` doesn't support naming a file directly, but I'm sure there is a workaround somehow, maybe without `JavaFile.builder` and `OutputStreams`.  But I haven't time to test it right now.

**Comment by themadhukiran** [comment]
Oh! Will try it out and let you know how it goes. Thanks.

**Comment by sockeqwe** [comment]
as already said, I'm not entirely sure that this works, but I hope so

**Comment by AndreasBoehm** [comment]
Fixed by #104

**Comment by sockeqwe** [comment]
Thanks a lot @AndreasBoehm

**Comment by sockeqwe** [comment]
@AndreasBoehm I'm not sure if you are living in Munich  like I do (your github profile says so) but I'm really thankful for all your contributions and would love to invite you for lunch somewhen (soonish)! Let me know what you think about it and which date / time works best for you ...
