### ISSUE TITLE
Unable to reference generated builder in java/kotlin project.

### ISSUE THREAD

**Issue by fabiocarballo** [sockeqwe/fragmentargs#34]
Hey,

I'm trying to integrate Kotlin on my project and I'm using the fragmentArgs 3.0.0 version. However, when I try to reference a generated builder in the Kotlin class I always  get the error: Unresolved reference: LoadingDialogBuilder (on my case). The LoadingDialogFragment is a java class annotated with @FragmentWithArgs 

I've also added kapt (...) to my project.

Do you have any advice on how to approach this problem?

Thank you.

**Comment by sockeqwe** [comment]
Hi,
do you have set `generateStubs = true` ?

```groovy
kapt {
  generateStubs = true
}

dependencies {
    compile 'com.hannesdorfmann.fragmentargs:annotation:3.0.0'
    kapt 'com.hannesdorfmann.fragmentargs:processor:3.0.0'
}
```

**Comment by fabiocarballo** [comment]
Hi, I was missing the generateStubs bit. 

However when I add the
```
kapt {
  generateStubs = true
}

```

I get this when building the project:
```
Please do not use `com.neenbedankt.android-apt` with kapt.
````

**Comment by sockeqwe** [comment]
This is just a warning to prevent conflicts between `kapt` (kotlin annotation processor) and `apt` (android annotation processor by using 'com.neenbedankt.android-apt' gradle plugin). 
just remove this from your `gradle.build` script
```groovy
apply plugin: 'com.neenbedankt.android-apt'
```

and use `kapt` instead of `apt` in `dependencies {  ... }` block
