### ISSUE TITLE
actual argument Object cannot be converted to ... by method invocation conversion

### ISSUE THREAD

**Issue by Shargotth** [sockeqwe/fragmentargs#35]
Hi,

Im' using Parceler and FragmentWithArgs together and I'm getting some trouble when it comes to parse an object that inherits from a superclass. The exact error I get is : 

> actual argument Object cannot be converted to MySubClass by method invocation conversion". 

At the line _**fragment.setmyField(bundler1.get("myField", args) );**_ In the method _**injectArguments**_.

My classes look like this : 

```java
@Parcel
public class Parent {
    int field1;
    int field2;
    String field3;
    Date field4;
    // ...

    // Setters & getters
}

@Parcel
public class MySubClass extends Parent {
    int filed5;
    String field6;
    // ...

    // Setters & getters
}
 ```

Thank you in advance for your help.

**Comment by sockeqwe** [comment]
Hi, 
can you please post your `Fragment` and the generated `FragmentBuilder` (have a look into `app/build/generated/source/apt/` folder)

**Comment by BraunreutherA** [comment]
I had the same problem. It works when you set the Field public in the Fragment but not as a private one.

**Comment by sockeqwe** [comment]
I'm not to sure how `@Parcel` annotated classes are related to this issue. As @BraunreutherA  suggest, most likely there is an visibility issue when accessing the fragments field. If you annotate a private field with `@Arg` than the FragmentArgs should throw an compile error if no public setter method for this private field has been found. 

If not, then it might be bug of FragmentArgs. If so, it would be really helpful if you could post an example where the bug occurs (fragment source code)

**Comment by BraunreutherA** [comment]
This is the parcel class I use: 
```java
@Parcel
public class AuthData {
    String username;
    String password;
    String phoneNumber;
    String pictureUrl;
}
```

Here we got the annotated fragment:
```java
@FragmentWithArgs
public class LoginFragment extends BaseFragment {
    @Arg
    private boolean animated;

    @Arg( bundler = ParcelerArgsBundler.class )
    private AuthData authData;

    @Bind(R.id.login_username)
    UsernameTextField username;

    @Bind(R.id.login_password)
    EditableTextField password;

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        ...
    }

    @Override
    protected int getLayoutRes() {
        ...
    }

    public void setAnimated(boolean animated) {
        this.animated = animated;
    }

    public void setAuthData(AuthData authData) {
        this.authData = authData;
    }
}
```

That way I get the same error.

If I change the fragment to:
```java
@FragmentWithArgs
public class LoginFragment extends BaseFragment {
    @Arg
    private boolean animated;

    @Arg( bundler = ParcelerArgsBundler.class )
    AuthData authData;

    @Bind(R.id.login_username)
    UsernameTextField username;

    @Bind(R.id.login_password)
    EditableTextField password;

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        ...
    }

    @Override
    protected int getLayoutRes() {
        ...
    }

    public void setAnimated(boolean animated) {
        this.animated = animated;
    }
}
```

So it seams to be the parcelBundler or the parceler cause the bool field works as private field.

**Comment by sockeqwe** [comment]
Thanks for the feedback.
Now I see the problem.

There is an issue when dealing with generics:

```java
public class ParcelerArgsBundler implements ArgsBundler<Object> {

 @Override public <V> V get(String key, Bundle bundle) {
    return Parcels.unwrap(bundle.getParcelable(key));
  }
}
```

The generated code looks like this:
```java
 fragment.setAuthData( bundler1.get("authData", args) ); 
```
But somehow there is an issue with generics, because the parameter type of the setter cannot be determined in `<V> V get(...)`. I'm not sure why, but I will investigate on that.

When you remove the "private" visibility of authData Field then the field will be accessed directly and **not** via setter method. By directly accessing the field the generics can be resolved dynamically in   `<V> V get(...)`.

The generated code looks like this:
```java
fragment.authData = bundler1.get("authData", args);
```

**Comment by sockeqwe** [comment]
I have release `3.0.1` containing a fix for that issue
