### ISSUE TITLE
Frozen uses Serializable instead of Parcelable interface when both are used

### ISSUE THREAD

**Issue by NeveHanter** [sockeqwe/fragmentargs#38]
When CountryModel implements Parcelable and Serializable interfaces, later is used instead of the first.

Ex.:
warning: mCountry will be stored as Serializable
    @Frozen CountryModel    mCountry;

for:
```java
public class CountryModel
        implements Serializable, Parcelable {
}
```

**Comment by sockeqwe** [comment]
I see, I will consider that in next update. Changing the order of `implements` might work as temporarly workaround. 

```java
public class CountryModel
        implements Parcelable, Serializeable
```

**Comment by NeveHanter** [comment]
Sorry about that issue, actually I've mistaken your library with https://bitbucket.org/hvisser/bundles library I'm using in my project to generate builders for fragments.
