### ISSUE TITLE
Missing AutoFragmentArgInjector

### ISSUE THREAD

**Issue by gelldur** [sockeqwe/fragmentargs#40]
Class AutoFragmentArgInjector is not generated? What i'm missing?

**Comment by sockeqwe** [comment]
How does your `build.gradle` looks like? Do you use `apt` ?Are you using fragmentargs in a library project? Do you have incremental builds enabled?

**Comment by gelldur** [comment]
1. I don't have incremental builds ( Android Studio 1.5.1 ) (Clean -> Build don't help)
2. I'm using in my app not in lib
3. 
build.gradle
```
+apply plugin: 'com.neenbedankt.android-apt'
...
+apt {
+	arguments {
+		fragmentArgsLib true
+	}
+}
...
+	compile 'com.hannesdorfmann.fragmentargs:annotation:3.0.1'
+	apt 'com.hannesdorfmann.fragmentargs:processor:3.0.1'
```

Project build.gradle
`+		classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'`

**Comment by sockeqwe** [comment]
If not used in a library, then you have to remove this:
```
apt {
+   arguments {
+       fragmentArgsLib true
+   }
```
The rest is fine!
+}

**Comment by gelldur** [comment]
Ok thanks i misunderstood ;)
