### ISSUE TITLE
Parceler support?

### ISSUE THREAD

**Issue by MarcinOrlowski** [sockeqwe/fragmentargs#41]
While I am aware of ParcelablePlease, is there any chance of having @Parcel annotated classes to be supported by FragmentArgs too?

**Comment by sockeqwe** [comment]
yes, fragmentargs has a "plugin" system to put "not parcelable" datastructures into fragment's argument bundle. See thre README (chapter ArgsBundler). There is already such a "bundler" for Parceler provided. You just have to add the dependnecy (see README).
