### ISSUE TITLE
Support activity parameter

### ISSUE THREAD

**Issue by brucexia** [sockeqwe/fragmentargs#43]
It's neat with Fragment...how about extend that to Activity as well? e.g.
@ActivityWithArg?

**Comment by sockeqwe** [comment]
There are already other libraries doing this job. I think this library should be stayed focused on Fragments.

**Comment by lectricas** [comment]
@sockeqwe can you name some examples of such libraries?
Btw, it will be nice to have all activity/fragment params in one lib and having the same syntax.

**Comment by sockeqwe** [comment]
@lectricas This one for example:
https://github.com/emilsjolander/IntentBuilder
