### ISSUE TITLE
Kotlin "is" prefix for booleans

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/fragmentargs#46]
Kotlin is treating boolean fields slightly different when generating getters and setters compared to other "usual" baking fields.

https://github.com/sockeqwe/sqlbrite-dao/issues/27

**Comment by johncarl81** [comment]
We recently had a similar issue reported too: https://github.com/johncarl81/parceler/issues/162  I noticed that Intellij will generate the following getter/setter for "`boolean isValue`": `isValue()` and `setValue()`.  Does the Java Bean spec mention this?

**Comment by sockeqwe** [comment]
I have no clue. I guess kotlin have chosen that for better readability. Actually, kotlin is not not checking the type. Also a field of type string like `val isFoo : String` will translate to `isFoo()` and `setFoo(string)`

**Comment by marchy** [comment]
What is the resolution on this? Almost abandoned the library going crazy trying to chase this before running across this post.
