### ISSUE TITLE
Prevent too much compilation error messages

### ISSUE THREAD

**Issue by sockeqwe** [sockeqwe/fragmentargs#51]
If one `Fragment` annotated with `@Arg` fails (i.e. not parcelable see #50), then no `Builder` is generated for the other `Fragment` that are annotated properly. This should be possible to optimize by generating `Builder` classes directly and not after having scanned the whole source code.

Maybe I have to temporarely queue error messages (instead of printing them directly which may cause javac to stop instead of continuing with other valid fragments) to ensure that all properly annotated Fragments will generate their corresponding Builders.

**Comment by AndreasBoehm** [comment]
Looks like this has been fixed in the referenced commit from 27 Mar 2016 👍
