### ISSUE TITLE
Use Parcelable instead of Parceler

### ISSUE THREAD

**Issue by Martin-Hogge** [sockeqwe/fragmentargs#52]
Hi,

For some reason I don't want to Parcel my POJO classes with Parceler. I just add Parcelable implementation to them.

But when I do this and want to use "@Arg" to one of these classes I got this exception : 

> error: method setmMyPojo in class MyPojoFragment cannot be applied to given types;
> required: MyPojo 
> found: Parcelable
> reason: actual argument Parcelable cannot be converted to MyPojo by method invocation conversion

I know their is a bundler for Parceler but is there a way to use Parcelable objects?

Thank's.

**Comment by sockeqwe** [comment]
I'm sorry, that should work out of the box. It seems that this is a bug. Could you please post your annotated Fragment and the generated Builder, so that I can reproduce and fix this issue.

Are you annotating a private field with `@Arg` right?

**Comment by Shargotth** [comment]
Well yes I was annotating a private field. Private fields was working with Serializable stuff so I didn't think of it but made them public did the trick.

Thank's for your help and great job for this useful library !

**Comment by sockeqwe** [comment]
Well, it should work with private fields if you provide a corresponding public setter method.

So I think this is a bug. 

Could you please show me how you have annotated your Fragment class and setter for the annotated arguments, so I can fix it ...

**Comment by Shargotth** [comment]
This is what's how my Fragment look like : 

```
@FragmentWithArgs
public class HomeSmallBannerFragment extends BaseFragmentArgs {

    @Arg
    private Match mMatch;

    //Some stuffs...

    //setters
    public void setmMatch(Match mMatch) {
        this.mMatch = mMatch;
    }

}
```

And this is how my "BaseFragmentArgs look like : 

```
public class BaseFragmentArgs extends Fragment {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        FragmentArgs.inject(this);
    }

}
```

Hope this helps.

**Comment by sockeqwe** [comment]
Thanks!
And `class Match implements Parcelable {} `, right?

btw. it should be enough to make field `match`  package visible (default visibility) to work with FragmentArgs properly:

```java
@FragmentWithArgs
public class HomeSmallBannerFragment extends BaseFragmentArgs {

    @Arg
    Match mMatch;   // not public, not private
}
```

**Comment by AndreasBoehm** [comment]
Looks like this issue is not present in 4.0.0-SNAPSHOT from latest master @sockeqwe
