### ISSUE TITLE
Builder is not generated for fragment without any @Arg annotated memeber

### ISSUE THREAD

**Issue by MarcinOrlowski** [sockeqwe/fragmentargs#54]
I am  in process of reducing boilerplate code and I would like to all my Fragments to use FragmentArgs. As part of unification I'd like to **always** instantiate my fragments using FragmentArgs' generated builder class, however it seems that version 3.x is not generating any builder if fragment annotated with `@FragmentWithArgs` got no members annotated with `@Arg`. Unless I miss something obvious here I believe this is a bug in the lib as there should be no reason that could prevent having builder in such case.

The workaround which I am using now is to simply add:

    @Arg(required = false)
    boolean foo;

but naturally this pollutes the code. Any comments welcome. Thanks

**Comment by sockeqwe** [comment]
Which version do you use? This should already been fixed in 3.0.2 
Dont forget to use 3.0.2 apt processor too.

Alternatively there is a 4.0.0-SNAPSHOT available on 
```
maven { url "https://oss.sonatype.org/content/repositories/snapshots" } } 
```

**Comment by MarcinOrlowski** [comment]
I am using 3.0.2:

    compile 'com.hannesdorfmann.fragmentargs:annotation:3.0.2'
    compile 'com.hannesdorfmann.fragmentargs:bundler-parceler:3.0.2'
    apt 'com.hannesdorfmann.fragmentargs:processor:3.0.2'

**Comment by sockeqwe** [comment]
Hm, so with empty fragment you mean something like this, right?
https://github.com/sockeqwe/fragmentargs-samples/blob/master/app/src/main/java/com/hannesdorfmann/fragmentargstest/EmptyFragment.java

In this sample project in compiles without any issues

```java
public final class EmptyFragmentBuilder {

  private final Bundle mArguments = new Bundle();

  public EmptyFragmentBuilder() {
  }

  public static final void injectArguments(@NonNull EmptyFragment fragment) {
  }

  @NonNull
  public EmptyFragment build() {
    EmptyFragment fragment = new EmptyFragment();
    fragment.setArguments(mArguments);
    return fragment;
  }

  @NonNull
  public <F extends EmptyFragment> F build(@NonNull F fragment) {
    fragment.setArguments(mArguments);
    return fragment;
  }
}
```

**Comment by MarcinOrlowski** [comment]
when you think 4.0 could be officially released?

**Comment by sockeqwe** [comment]
in about a week
