### ISSUE TITLE
Create the fragments passing its class

### ISSUE THREAD

**Issue by bryant1410** [sockeqwe/fragmentargs#57]
This came to my mind when refactoring certain behavior. I wanted to create a FragmentPagerAdapter that works only passing an enum and the Fragment class, creating it with FragmentArgs. But I found out that I cannot relate (or at least I don't know how) a Fragment with its builder. This is what I've done:

```java
public class EnumPagerAdapter<E extends Enum<E>, F extends BaseFragment> extends FragmentPagerAdapter {
  private final List<F> fragments;

  public EnumPagerAdapter(FragmentManager fragmentManager, Class<E> enumClass, Func1<E, F> fragmentCreator) {
    super(fragmentManager);
    fragments = Stream.of(enumClass.getEnumConstants())
        .map(fragmentCreator::call)
        .collect(Collectors.toList());
  }

  @Override
  public F getItem(int position) {
    return fragments.get(position);
  }

  @Override
  public int getCount() {
    return fragments.size();
  }
}
```

Right now it asks for a `fragmentCreator` method, but as I said before I wanted it to be created by FragmentArgs and pass it the enum instance.

This made me realize that it'd be useful if the way that the builder is created is could be passing the fragment class (like Retrofit's `create`: `FragmentArgs.create(ExampleFragment.class)`). Besides, this has the advantage that code compiles without the need to build the project for the first time when a new fragment is used. And still a compile-time error can be thrown if a problem is found while creating the builder.

**Comment by bryant1410** [comment]
I think the implementation of this could be achieved with a map between `Class` and the fragment builders.

**Comment by sockeqwe** [comment]
I think this is out of scope of this library. 
Furthermore, if there would be something like `FragmentArgs.create(ExampleFragment.class))` this will not work because each Fragment has different Arguments, hence each builder will have different constructor parameters etc. 

This mapping is something you have to do on your own, i.e. a `switch` statement on an enum wouldn't be too complicated to implement...

**Comment by bryant1410** [comment]
Ok. Builder parameters could be passed after the creation of the builder also.

**Comment by sockeqwe** [comment]
but what would be the return type of `FragmentArgs.create(ExampleFragment.class))` ?
`ExampleFragmentBuilder`? That can't be estimated without reflection at runtime. 

We could make breaking changes and use Generics `FragmentBuilder<? extends ExampleFragment>`, then  `FragmentArgs.create(ExampleFragment.class))` would know at compile time the return type `FragmentBuilder<ExampleFragment>` but still, the concrete implementation of `FragmentBuilder<ExampleFragment>` with the corresponding method to set ExampleFragment's argument can't be known at this point.

**Comment by bryant1410** [comment]
Maybe something like `FragmentArgs.builderOf(ExampleFragment.class).create(args...)`, so that `FragmentArgs.builderOf(ExampleFragment.class)` returns the builder, which instead of accepting the parameters in its constructor, it creates the Fragment from a `create` method.

Another (more disruptive) option that came to my mind is to imitate what [dart](https://github.com/f2prateek/dart) does. In a nutshell, it would be getting the builder from the mapping and then something like accepting the mandatory parameters the same way that the optional ones, but  in a certain order and don't letting to build the instance until all is "all set".

**Comment by sockeqwe** [comment]
I don't know how `FragmentArgs.builderOf(ExampleFragment.class).create(args...)` this could be implemented in a type safe manner. 

> Another (more disruptive) option that came to my mind is to imitate what dart does. In a nutshell, it would be getting the builder from the mapping and then something like accepting the mandatory parameters the same way that the optional ones, but in a certain order and don't letting to build the instance until all is "all set".

This would remove compile time validation that all required arguments are set of a Fragment because only at runtime we can check if all arguments are set. Therefore its not an option for me.

**Comment by bryant1410** [comment]
Regarding the second option, [dart enforces the validation at compile time](https://github.com/f2prateek/dart/blob/485cc96bda4304c122517c9075b788c29e2d16a5/henson-processor/src/main/java/com/f2prateek/dart/henson/processor/IntentBuilderGenerator.java#L139). So you have to put all required args (and in a certain order) to build the `Intent`.

**Comment by bryant1410** [comment]
Yes, this is hard to generify correctly (without using `Bundle`) and is not worth it.

In the class given in the initial comment a generic approach would be something that uses `Bundle` and is correctly interpreted by FragmentArgs injector. If think it would work for fragments which receive only 1 object of the given enum and its name complies with certain format (such as being equal to the enum name).
