### ISSUE TITLE
Inner Class Support

### ISSUE THREAD

**Issue by TUBB** [sockeqwe/fragmentargs#59]
Thanks for making such a good library.

Inner class (nest Fragment in the Activity) not supported yet?

**Comment by sockeqwe** [comment]
Not yet, but will  fix that in upcoming major release

Pobi <notifications@github.com> schrieb am Mo., 9. Mai 2016, 11:19:

**Comment by sockeqwe** [comment]
Correction: per se it works, but there is an issue with inner classes.
So if you have a Fragment calles FooFragment in `com.example.MyActivity.FooFragment` and the another "standalone" Fragment called `com.example.FooFragment` (same package as nested Activity Fragment) then there is a bug that will create the same FragmentBuilder with the same name for both Fragments which is a bug

**Comment by TUBB** [comment]
Yes, it is a bug in this special case.
I use ( entry.getKey().getNestingKind().isNested() ) to know the FooFragment is nested Activity Fragment or not.
But i have no way to know that in AutoFragmentArgInjector.

**Comment by AndreasBoehm** [comment]
With version 3.0.2 and 4.0.0-SNAPSHOT the project won't compile with a annotated inner class.

- Import for `{FragmentName}` missing in `{FragmentName}Builder.java`
- `AutoFragmentArgInjector` tries to use `com.example.MyActivity.FooFragmentBuilder` but the builder is located under `com.example.FooFragmentBuilder`

We could either add the import and correct the `AutoFragmentArgInjector` or adjust code generation for inner classes to generate the Builder as inner class as well (`MyActivity$$FooFragment`). This would also fix #33
