### ISSUE TITLE
CastedArrayListArgsBundler gives compilation errors.

### ISSUE THREAD

**Issue by fmnstr** [sockeqwe/fragmentargs#60]
I get the following error when trying to use CastedArrayListArgsBundler as a bundler for an Arraylist of parcelable object.

`Error:(32, 35) error: incompatible types: List<CAP#1> cannot be converted to List<Foo>
where CAP#1 is a fresh type-variable:
CAP#1 extends Parcelable from capture of ? extends Parcelable`

in my fragment

`    @Arg(bundler = CastedArrayListArgsBundler.class) List<Foo> foobar;`

and my foo class 

`public class Foo implements Parcelable {
        String happy;

        @Override
        public int describeContents() {
            return 0;
        }

        @Override
        public void writeToParcel(Parcel dest, int flags) {
            dest.writeString(this.happy);
        }

        public Foo() {
        }

        protected Foo(Parcel in) {
            this.happy = in.readString();
        }

        public static final Parcelable.Creator<Foo> CREATOR = new Parcelable.Creator<Foo>() {
            @Override
            public Foo createFromParcel(Parcel source) {
                return new Foo(source);
            }

            @Override
            public Foo[] newArray(int size) {
                return new Foo[size];
            }
        };
    }`

the error is here in the Builder class

`  public static final void injectArguments(@NonNull InterestRateDetailsFragment fragment) {
    Bundle args = fragment.getArguments();
    if (args == null) {
      throw new IllegalStateException("No arguments set. Have you setup this Fragment with the corresponding FragmentArgs Builder? ");
    }

    if (!args.containsKey("com.hannesdorfmann.fragmentargs.custom.bundler.2312A478rand.foobar")) {
      throw new IllegalStateException("required argument foobar is not set");
    }
    fragment.foobar = bundler1.get("foobar", args); //<-------error here
  }`

using latest gradle and build tools

**Comment by sockeqwe** [comment]
Thanks for reporting. It seems that this is a bug

**Comment by f0restgump92** [comment]
Any solutions for this?

**Comment by sockeqwe** [comment]
Will try to reproduce and fix this in about two weeks...

Ivan Milisavljevic <notifications@github.com> schrieb am Fr., 5. Aug. 2016,
14:56:

**Comment by kosmonastya** [comment]
Any updates or workarounds, guys? I stuck a bit with this thing :(

**Comment by f0restgump92** [comment]
@kosmonastya You can create a new model class with the List as member and use the ParcelerArgsBundler. Check out this [https://gist.github.com/f0restgump92/76ada8f5d526ead6581b75914f5af80c](gist) for more details.
It's not the best solution but should do the trick

**Comment by kosmonastya** [comment]
All right, works this way! But then I passed as @Arg just an ArrayList<Foo> without any bundler and all good

**Comment by sockeqwe** [comment]
This is fixed in latest `4.0.0-SNAPSHOT`
