### ISSUE TITLE
Allow protected fields to be used as arguments

### ISSUE THREAD

**Issue by pamalyshev** [sockeqwe/fragmentargs#61]
For example when we write in our fragment something like this:

```
@Arg
protected String protectedArg;
```

We'll get an error:

> Error:(6, 22) error: The @Arg annotated field 'protectedArg' in class ClassWithProtectedField has private or protected visibility...

I wonder why `protected` fields can't be used as arguments. `FragmentBuilder#injectArguments` can access them because `FragmentBuilder` is in the same package as `Fragment`. I've created a test in https://github.com/pamalyshev/fragmentargs/commit/05350b0a472f381648af56647122edf84baa88cc

**Comment by sockeqwe** [comment]
I might be wrong, but protected fields are only visible and accessible from subclasses. `FragmentBuilder` is not a subclass of `Fragment`

**Comment by pamalyshev** [comment]
According to https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html
>The protected modifier specifies that the member can only be accessed within its own package (as with package-private) and, in addition, by a subclass of its class in another package.

**Comment by stavfx** [comment]
Yes, @pamalyshev is correct, `protected` fields only add access to subclasses on top of the default `package-local` access.
Can we have support for `protected` fields?

**Comment by sockeqwe** [comment]
Yes, I will add support for that

**Comment by AndreasBoehm** [comment]
Hey @sockeqwe,
I will try to get this done tonight so we could have it for version 4.0?

**Comment by sockeqwe** [comment]
Awesome, thanks!
