### ISSUE TITLE
Suggestion: improve setter generation

### ISSUE THREAD

**Issue by rubenweerts** [sockeqwe/fragmentargs#68]
When I have a field named `protected String _title`, the library looks for `set_title()` setter method. Instead I would love to see that the library ignores the prefix and looks for `setTitle()`.

I've tried setting the `@Args(key = "")` value but this has no impact on what setter method is being generated. Maybe use `set[key]` as formatting for setter generation?

**Comment by sockeqwe** [comment]
`key` is meant for the Bundle key. I already remove the m prefix, so I guess it won't hurt to remove _ prefix too, although I'm not sure how many java developers are using the underscore prefixing convention ...

**Comment by rubenweerts** [comment]
I don't think it's very common, but there are quite some projects done with non-standard coding conventions. IMHO should a library never be dependent on a coding convention, but I know it's hard to support them all.

Already looking forward to the next release 👍
