### ISSUE TITLE
Doesn't work with new kotlin experimental annotation processor

### ISSUE THREAD

**Issue by NitroG42** [sockeqwe/fragmentargs#69]
When using the experimental "apply plugin: 'kotlin-kapt'" (https://discuss.kotlinlang.org/t/kotlin-1-0-4-eap/1901/3), the builder generated will all have an empty constructor.
Here's a sample project : 
[MyApplication.zip](https://github.com/sockeqwe/fragmentargs/files/455365/MyApplication.zip)

Here's the kotlin issue : https://youtrack.jetbrains.com/issue/KT-13733

**Comment by NitroG42** [comment]
It was a kotlin issue !

**Comment by sockeqwe** [comment]
Thanks!
