### ISSUE TITLE
ErrorProne warns AutoFragmentArgInjector does not use @Override annotation

### ISSUE THREAD

**Issue by danielevitali** [sockeqwe/fragmentargs#73]
I am using [ErrorProne](https://github.com/google/error-prone) as static analyzer of my code.
I see one easy-to-fix- warning coming from FragmentArgs.

```
app/build/generated/source/apt/debug/com/hannesdorfmann/fragmentargs/AutoFragmentArgInjector.java:7: warning: [MissingOverride] inject implements method in FragmentArgsInjector; expected @Override
  public void inject(Object target) {
              ^
    (see http://errorprone.info/bugpattern/MissingOverride)
  Did you mean '@Override public void inject(Object target) {'? 
```

In a nutshell, it just warns to add `@Override` to the inject method of the `AutoFragmentArgInjector` class.

**Comment by sockeqwe** [comment]
Thanks for reporting. This is easy to fix. I will do that during holidays. Merry Christmas and happy holidays.
