### ISSUE TITLE
Takes Serializable instead of Parcelable

### ISSUE THREAD

**Issue by seppelandrio** [sockeqwe/fragmentargs#74]
If a class implements Serializable and Parcelable, the object is being stored as Serializable in Bundle instead of saving it as more efficient Parcelable construct.

Simple Example:
`@FragmentWithArgs
public class MyFragment extends Fragment {
    @Arg
    Test test;
}`
with Test class:
`
public class Test implements Serializable, Parcelable {

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
    }

    public Test() {
    }

    protected Test(Parcel in) {
    }

    public static final Creator<Test> CREATOR = new Creator<Test>() {
        @Override
        public Test createFromParcel(Parcel source) {
            return new Test(source);
        }

        @Override
        public Test[] newArray(int size) {
            return new Test[size];
        }
    };
}
`

**Comment by seppelandrio** [comment]
Comment:
Does work in 4.0.0-SNAPSHOT

**Comment by sockeqwe** [comment]
yep, the order has been fixed in `4.0.0`
