### ISSUE TITLE
Controller support

### ISSUE THREAD

**Issue by MFlisar** [sockeqwe/fragmentargs#76]
Did you ever yet think about supporting conductor controllers? As you seem to use them as well instead of fragments, that would be really nice...

**Comment by sockeqwe** [comment]
Yes, its on my todo list, but my todo list is very long :) and it has not
the highest priority right now ...

MFlisar <notifications@github.com> schrieb am Di., 14. Feb. 2017, 09:29:

**Comment by MFlisar** [comment]
Will you make a new library or merge it into this one?

**Comment by sockeqwe** [comment]
My plan was / is to move the internal code generation of fragmentargs into is own .jar library which then will be included as dependency by both, fragmentargs and the conductor pandon (controllerargs maybe 😂). To sum it up, yes i will create a separate library for conductor, with his own annotations and so on (but it will share the internal code generation code with fragmentargs)

https://github.com/bluelinelabs/Conductor/issues/7
https://github.com/bluelinelabs/Conductor/issues/3

**Comment by MFlisar** [comment]
I thought about copying your project and just adjust it to work with conductor instead of fragments... It would be my first processor, so cleaning the code and extracting the core functions would probably be too much for me now...

**Comment by MFlisar** [comment]
FYI:

OK, after some time reading a simple project, I made a generic bundle builder that works with any class... It can be used for conductor as well: https://github.com/MFlisar/BundleArgs... This is the first draft though and I'll make a few improvements...

As you have the other issues open in the conductor project, you can close this one if you want to

**Comment by sockeqwe** [comment]
Awesome! Thanks!
