### ISSUE TITLE
Add support for Kotlin nullables

### ISSUE THREAD

**Issue by marchy** [sockeqwe/fragmentargs#80]
Hi there, it seems the library does not support nullable Kotlin arguments. This actually has nothing to do with FragmentArg's notion of 'optional' – ie: it's perfectly valid to have either a required or optional nullable property. Currently the library does not support optional non-nullable fields, it seems to require.

Currently if you try the following:
``` Kotlin
@Arg( required = false ) var place:Place? = null
```
you get the following compilation error:
```error: Don't know how to put xxx.models.Place in a Bundle. This type is not supported by default. However, you can specify your own ArgsBundler implementation in @Arg( bundler = YourBundler.class)```

Currently the only workaround is to wrap the field with a nullable accessor and supress Kotlin's UninitializedPropertyAccess exception (intricate hack)
``` Kotlin
// HACK for FragmentArgs lack of support for optionals
@Arg( required = false ) lateinit var place_:Place
private val place:Place?
    get() {
        try {
            @Suppress( "UNUSED_EXPRESSION" )
            return place_
        } catch( x:UninitializedPropertyAccessException ){
            return null
        }
    }
```

We need 1st-hand support for Kotlin optionals in FragmentArgs, especially since this is a core use-case for any optional field (ie: by definition they should be nullable).

**Comment by sockeqwe** [comment]
Are you sure that `Place` is ìmplementing `Parcelable`?

**Comment by marchy** [comment]
Thanks for the super fast response Hannes. Apologies I put in the wrong error.
The actual error is ```error: incompatible types: Parcelable cannot be converted to Where
      fragment.setWhere_( args.getParcelable("where_") );```

Do I take it then that the issue then that the parcel library we are using (PaperParcel) isn't supporting Kotlin nullables?

**Comment by sockeqwe** [comment]
No worries ... Which version of FragmentArgs are you using.

**Comment by marchy** [comment]
Latest - FragmentArgs 3.0.2

And yes, Place is parcelable, the non-nullable version above works just fine.
Looking into it further it seems it works with nullable primitives (ie: String) but not nullable objects.

**Comment by sockeqwe** [comment]
Can you try it with latest 4.x SNAPSHOT. I think this has already been fixed.

**Comment by marchy** [comment]
Wonderful, yes it has  =)

Any idea of when you're targeting 4.0.0 to be released?

**Comment by sockeqwe** [comment]
The plan was to release it a year ago :)

Unfortunately I haven't had much time for this project. Not sure if I can
work on it before August. if you would like to contribute you would be more
than welcome to do so.

Marcel Bradea <notifications@github.com> schrieb am Di., 23. Mai 2017,
18:59:
